### ISSUE TITLE
comparability

### ISSUE THREAD

**Issue by XDeeX4** [Paget96/L_SPEED#5]
I m using franco kernel already. Can i still use this L speed. Are there any significant changes or should i not use it along side with feanco kernel?

**Comment by Paget96** [comment]
Sure, you can ;) it's much better with custom kernel.

**Comment by Paget96** [comment]
Hey,

I just signed the petition "Google developer support: Google, Ruined
Start-Up of Android Career by Suspending App #bringbackfreespinsandcoins"
and wanted to see if you could help by adding your name.

Our goal is to reach 1,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/mQsHkr888G

Thanks!
Danijel
