### ISSUE TITLE
L speed latest apk V2.1.4

### ISSUE THREAD

**Issue by Raunak1819** [Paget96/L_SPEED#6]
I want to ask something ... regarding the l speed app ... Eveytime I apply/turn on the CPU /GPU tuner do I have to rebbot the phone everytime to make it work ...? Can you  help me ...

**Comment by Paget96** [comment]
No need

**Comment by Mo89oN** [comment]
Wow

**Comment by alcestneige** [comment]
Hello,have mi note 10 with dev miui 11 and can not create profil backup with l speed, it says backup created,but there is none. Any idea? Thanks

**Comment by Paget96** [comment]
> Hello,have mi note 10 with dev miui 11 and can not create profil backup with l speed, it says backup created,but there is none. Any idea? Thanks

Are you on the latest version?

**Comment by alcestneige** [comment]
Hello,two versions back from the rom,app is latest. Thanks

**Comment by alcestneige** [comment]
> Hello,two versions back from the rom,app is latest. Thanks

Thanks,in 1.5 problem was fixed.
