### ISSUE TITLE
App crashing when performing any task on Redmi 5 Plus

### ISSUE THREAD

**Issue by aimdloop** [Paget96/L_SPEED#9]
Crash log url-https://del.dog/yuhakisulo

**Comment by Paget96** [comment]
Thanks, I'll do a check

**Comment by aimdloop** [comment]
Have u find anything wrong whats going on?Btw i changed my custom rom yesterday.And its solve the problem.Now the apk is working fine.You can close this issu if u want.

**Comment by Paget96** [comment]
Thanks for reporting
